server:
  port: 8084
spring:
  application:
    name: ApiGateway
#  cloud:
#    gateway:
#      routes:
#        - id: USERSERVICE
#          url: lb://USERSERVICE
#          predicates:
#            - Path=/users/**
#
#        - id: HOTELSERVICE
#          url: lb://HOTELSERVICE
#          predicates:
#            - Path=/hotels/**
#
#        - id: RATINGSERVICE
#          url: lb://RATINGSERVICE
#          predictes:
#            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: Http://localhost:8761/eureka/
