server:
  port: 8083
spring:
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: RatingService
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 72524
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: Http://localhost:8761/eureka/